GET http://localhost:3030/user

####
GET http://localhost:3030/product?page=1

####
POST http://localhost:3030/product
Content-Type: application/json
    
    {
    "category":"xyz12",
    "title":"xyz12",
    "cover":"https://picsum.photos/200/300",
    "price":"xyz",
    "description":"xyz"
    
}
####
POST http://localhost:3030/user
Content-Type: application/json
    
    {
      
    "firstName": "xyz",
    "lastName": "xyz5",
    "email": "abcdef2@gmail.it",
    "password": "123456xyz5"

    
}

####
PATCH  http://localhost:3030/user/6620417fefd0643bbb789677
Content-Type: application/json
    
    {
    
    "email":"abc2@gmail.it"
    
}
####
DELETE http://localhost:3030/user/6620418eefd0643bbb789679
####


PATCH  http://localhost:3030/product/661fd2d8f1fb335917902aaa
Content-Type: application/json
    
    {
    
    "cover":"https://picsum.photos/200/300"
    
}
####
DELETE http://localhost:3030/product/6620416eefd0643bbb789675
####

POST  http://localhost:3030/login
Content-Type: application/json

{
    "email": "xyz5",
    "password": "xyz5"
}

####

GET http://localhost:3030/product/661fd2d8f1fb335917902aaa
